In [29]:
import pandas as pd

In [30]:
df_cp=pd.read_csv('codigos_postais.csv')

In [31]:
df_cp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326330 entries, 0 to 326329
Data columns (total 17 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   cod_distrito     326330 non-null  int64
 1   cod_concelho     326330 non-null  int64
 2   cod_localidade   326330 non-null  int64
 3   nome_localidade  326330 non-null  object
 4   cod_arteria      295208 non-null  float64
 5   tipo_arteria     292577 non-null  object
 6   prep1            158578 non-null  object
 7   titulo_arteria   43732 non-null   object
 8   prep2            4883 non-null    object
 9   nome_arteria     295208 non-null  object
 10  local_arteria    71556 non-null   object
 11  troco            38899 non-null   object
 12  porta            2889 non-null    object
 13  cliente          4149 non-null    object
 14  num_cod_postal   326330 non-null  int64
 15  ext_cod_postal   326330 non-null  int64
 16  desig_postal     326330 non-null  object
dtypes: float64(1), int64(5), object(11)
memory usage: 42.3+ MB

In [32]:
df_cp.head()

,cod_distrito,cod_concelho,cod_localidade,nome_localidade,cod_arteria,tipo_arteria,prep1,titulo_arteria,prep2,nome_arteria,local_arteria,troco,porta,cliente,num_cod_postal,ext_cod_postal,desig_postal
0,1,1,249,Alcafaz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,11,AGADÃO
1,1,1,250,Caselho,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,12,AGADÃO
2,1,1,251,Corga da Serra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,13,AGADÃO
3,1,1,252,Foz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,14,AGADÃO
4,1,1,253,Guistola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,15,AGADÃO

In [33]:
# 1. Primeiro, temos de garantir que as colunas são tratadas como texto (string)
df_cp['num_cod_postal'] = df_cp['num_cod_postal'].astype(str)
df_cp['ext_cod_postal'] = df_cp['ext_cod_postal'].astype(str)

In [34]:
# 2. Usar o zfill(3) na extensão para obrigar a ter sempre 3 dígitos
# Exemplo: '24' passa a '024', '5' passa a '005', '123' continua '123'
df_cp['ext_cod_postal'] = df_cp['ext_cod_postal'].str.zfill(3)
df_cp.head()

,cod_distrito,cod_concelho,cod_localidade,nome_localidade,cod_arteria,tipo_arteria,prep1,titulo_arteria,prep2,nome_arteria,local_arteria,troco,porta,cliente,num_cod_postal,ext_cod_postal,desig_postal
0,1,1,249,Alcafaz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,011,AGADÃO
1,1,1,250,Caselho,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,012,AGADÃO
2,1,1,251,Corga da Serra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,013,AGADÃO
3,1,1,252,Foz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,014,AGADÃO
4,1,1,253,Guistola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,015,AGADÃO

In [35]:
#Criar uma nova coluna com os sete digitos juntos
df_cp['CP7'] = df_cp['num_cod_postal'] + '-' + df_cp['ext_cod_postal']

In [36]:
df_cp.head()

,cod_distrito,cod_concelho,cod_localidade,nome_localidade,cod_arteria,tipo_arteria,prep1,titulo_arteria,prep2,nome_arteria,local_arteria,troco,porta,cliente,num_cod_postal,ext_cod_postal,desig_postal,CP7
0,1,1,249,Alcafaz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,011,AGADÃO,3750-011
1,1,1,250,Caselho,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,012,AGADÃO,3750-012
2,1,1,251,Corga da Serra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,013,AGADÃO,3750-013
3,1,1,252,Foz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,014,AGADÃO,3750-014
4,1,1,253,Guistola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,015,AGADÃO,3750-015

In [38]:
#Apenas deixo os valores que me interessam
df_cp= df_cp[['nome_localidade','num_cod_postal','ext_cod_postal','CP7']]
#Apenas os valores que começam por 4
df_cp = df_cp[df_cp['num_cod_postal'].str[0] == '4'].copy()

In [39]:
df_cp.head()

      nome_localidade num_cod_postal ext_cod_postal       CP7
2855            Mouta           4540            417  4540-417
2856       Espinheiro           4540            431  4540-431
2857        Corregato           4540            479  4540-479
2858  Olival da Tulha           4540            688  4540-688
2859         Pedregal           4540            218  4540-218

In [42]:
#Exportei o ficheiro para csv para dar merge
df_cp.to_csv('CodigoPostal.csv', index=False)